[package]
name = "slack_rs"
version = "0.1.0"
edition = "2021"
description = "A user-friendly Slack SDK implementation using slack-morphism-rust"

[dependencies]
slack-morphism = { version = "2.8", features = ["hyper", "axum"] }
tokio = { version = "1.35.0", features = ["rt-multi-thread", "macros"] }
axum = { version = "0.6", features = ["http1"] }
tracing = "0.1.40"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
dotenvy = "0.15"

[features]
default = ["socket_mode", "events", "oauth"]
socket_mode = ["slack-morphism/axum"]
events = []
oauth = []
