[package]
name = "slack_rs"
version = "0.1.0"
edition = "2021"
description = "A user-friendly Slack SDK implementation using slack-morphism-rust"

[dependencies]
slack-morphism = { version = "2.7.0", features = ["hyper"] }
tokio = { version = "1.35.0", features = ["full"] }
axum = { version = "0.7.9" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
hyper = { version = "0.14", features = ["client", "http1", "http2"] }
hyper-rustls = "0.23"


[dev-dependencies]
dotenvy = "0.15"

[features]
default = ["socket_mode", "events", "oauth"]
socket_mode = ["slack-morphism/hyper"]
events = ["dep:serde", "dep:serde_json"]
oauth = ["dep:serde", "dep:serde_json"]
