[package]
name = "slack_rs"
version = "0.1.0"
edition = "2021"
description = "A user-friendly Slack SDK implementation using slack-morphism-rust"

[dependencies]
slack-morphism = { version = "2.8", features = ["hyper"] }
tokio = { version = "1.35.0", features = ["full"] }
axum = { version = "0.7.9" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
tower = { version = "0.4", features = ["util"] }
hyper = { version = "0.14", features = ["full", "http1", "http2", "client", "tcp"] }
hyper-rustls = { version = "0.24", features = ["http1", "http2", "webpki-tokio"] }
tower-service = "0.3"
http = "0.2"
rustls = "0.21"


[dev-dependencies]
dotenvy = "0.15"

[features]
default = ["socket_mode", "events", "oauth"]
socket_mode = ["slack-morphism/hyper"]
events = ["dep:serde", "dep:serde_json"]
oauth = ["dep:serde", "dep:serde_json"]
