[package]
name = "slack_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
slack-morphism = { version = "2.7.0", features = ["hyper"] }
axum = "0.7.9"
tokio = { version = "1.35.0", features = ["full"] }
tracing = "0.1.40"

[dev-dependencies]
dotenvy = "0.15"

[features]
default = []
socket_mode = []
